# Generated by Django 5.2.1 on 2025-05-16 09:19

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique=True, verbose_name='Kompaniya nomi')),
                ('logo', models.ImageField(upload_to='company/', verbose_name='Kompaniya logotipi')),
                ('status', models.BooleanField(default=True, verbose_name='Holati')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqti')),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique=True, verbose_name='Viloyat nomi')),
                ('status', models.BooleanField(default=True, verbose_name='Holati')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqti')),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body_type', models.CharField(choices=[('Sedan', 'Sedan'), ('Krossover', 'Krossover'), ('Other', 'Other')], default='Sedan', max_length=250, verbose_name='Kuzov turi')),
                ('model', models.CharField(max_length=250, unique=True, verbose_name='Model nomi')),
                ('price', models.PositiveIntegerField(verbose_name='Narxi')),
                ('engine', models.CharField(max_length=250, verbose_name='Dvigatel hajmi')),
                ('km', models.IntegerField(verbose_name='Yurgan masofasi')),
                ('vin', models.CharField(max_length=250, unique=True, verbose_name='VIN raqami')),
                ('year', models.IntegerField(verbose_name='Ishlab chiqarilgan yili')),
                ('t_box', models.CharField(choices=[('Avtomatic', 'Avtomat'), ('Mechanic', 'Mexanika')], default='Avtomatic', max_length=250, verbose_name='Uzatmalar qutisi')),
                ('phone', models.CharField(max_length=13, validators=[django.core.validators.RegexValidator(message="Telefon raqami +998991232323 formatida bo'lishi kerak", regex='^[+]998[0-9]{9}$')], verbose_name='Telefon raqami')),
                ('image', models.ImageField(upload_to='car/', verbose_name='Avtomobil rasmi')),
                ('color', models.CharField(choices=[('Qora', 'Qora'), ('Oq', 'Oq'), ('Qizil', 'Qizil'), ('Yashil', 'Yashil'), ('Kulrang', 'Kulrang'), ('Sariq', 'Sariq'), ('Jigarrang', 'Jigarrang'), ('Boshqa', 'Boshqa')], default='Boshqa', max_length=250, verbose_name='Rangi')),
                ('fuel_type', models.CharField(choices=[('Benzin', 'Benzin'), ('Dizel', 'Dizel'), ('Gaz', 'Gaz'), ('Hibrid', 'Hibrid'), ('Elektr', 'Elektr')], default='Benzin', max_length=250, verbose_name="Yoqilg'i turi")),
                ('status', models.BooleanField(default=True, verbose_name='Holati')),
                ('about', models.TextField(blank=True, null=True, verbose_name="Batafsil ma'lumot")),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqti')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car.company', verbose_name='Kompaniya')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car.region', verbose_name='Viloyat')),
            ],
        ),
    ]
